module.exports = {
  SHOW_MODAL: 'MODAL/SHOW',
  HIDE_MODAL: 'MODAL/HIDE',
  HTTP_REQUEST: 'HTTP_REQUEST',
  HTTP_SUCCESS: 'HTTP_SUCCESS',
  HTTP_FAILURE: 'HTTP_FAILURE',
  HTTP_RESET: 'HTTP_RESET',
};
