module.exports = {
  RESERVE: 'RESERVE',
  RESET_RESERVE: 'RESET_RESERVE',
  RESERVE_REQUEST: 'RESERVE_REQUEST',
  RESERVE_SUCCESS: 'RESERVE_SUCCESS',
  RESERVE_FAILURE: 'RESERVE_FAILURE',
  SHOW_MODAL: 'MODAL/SHOW',
  HIDE_MODAL: 'MODAL/HIDE',
};
