module.exports = {
  SAVE_RESERVE_INFO: 'SAVE_RESERVE_INFO',
  SHOW_RESERVE: 'SHOW_RESERVE',
  RESERVE: 'RESERVE',
  RESET_RESERVE: 'RESET_RESERVE',
  RESERVE_REQUEST: 'RESERVE_REQUEST',
  RESERVE_SUCCESS: 'RESERVE_SUCCESS',
  RESERVE_FAILURE: 'RESERVE_FAILURE',
  BUTTON_CLICKED: 'BUTTON_CLICKED',
};
